CREATE TABLE `stock_realtime_full` ( 
   `code` varchar(20) NOT NULL COMMENT '股票代码（带sh/sz后缀）', 
   `name` varchar(50) DEFAULT NULL COMMENT '股票简称', 
   `price` decimal(10,2) DEFAULT NULL COMMENT '当前现价', 
   `pre_close` decimal(10,2) DEFAULT NULL COMMENT '昨日收盘价', 
   `open` decimal(10,2) DEFAULT NULL COMMENT '今日开盘价', 
   `high` decimal(10,2) DEFAULT NULL COMMENT '今日最高价', 
   `low` decimal(10,2) DEFAULT NULL COMMENT '今日最低价', 
   `volume` bigint DEFAULT NULL COMMENT '累计成交量（股）', 
   `amount` decimal(20,2) DEFAULT NULL COMMENT '累计成交额（元）', 
   `outer_vol` bigint DEFAULT NULL COMMENT '外盘（主动买，单位：股）', 
   `inner_vol` bigint DEFAULT NULL COMMENT '内盘（主动卖，单位：股）', 
   `buy1_price` decimal(10,2) DEFAULT NULL COMMENT '买一报价', 
   `buy1_vol` bigint DEFAULT NULL COMMENT '买一挂单量（股）', 
   `sell1_price` decimal(10,2) DEFAULT NULL COMMENT '卖一报价', 
   `sell1_vol` bigint DEFAULT NULL COMMENT '卖一挂单量（股）', 
   `recent_trade_time` datetime DEFAULT NULL COMMENT '最近一笔成交时间', 
   `pct_chg` decimal(10,2) DEFAULT NULL COMMENT '当日涨跌幅(%)', 
   `amplitude` decimal(10,2) DEFAULT NULL COMMENT '当日振幅(%)', 
   `turnover` decimal(10,2) DEFAULT NULL COMMENT '当日换手率(%)', 
   `pe` decimal(10,2) DEFAULT NULL COMMENT '动态市盈率', 
   `volume_ratio` decimal(10,2) DEFAULT NULL COMMENT '实时量比', 
   `mc_circ_billion` decimal(10,2) DEFAULT NULL COMMENT '流通市值（亿元）', 
   `mc_total_billion` decimal(10,2) DEFAULT NULL COMMENT '总市值（亿元）', 
   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '本地数据库最后更新时间', 
   PRIMARY KEY (`code`), 
   KEY `idx_pct_chg` (`pct_chg`) COMMENT '涨跌幅索引', 
   KEY `idx_mc` (`mc_circ_billion`) COMMENT '市值索引' 
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全市场分钟级实时行情快照表'; 
